---
title: "Prelim"
output: html_document
date: "2025-04-15"
---

```{r}
library(readxl)
library(dplyr)
library(skimr)
library(naniar)

library(tidyverse)
library(readxl)
library(pROC)
library(ROCR)
library(janitor)
```
```{r}
path <- "../"
filename <- "synthetic_data_stats_competition_2025_final.xlsx"

data <- read_excel(paste(path, filename, sep=""), sheet = "in")
```

#Summary stats
```{r}
data <- clean_names(data)

table(data$outcome_afib_aflutter_new_post)

summary(data$demographics_age_index_ecg) #Age
table(data$demographics_birth_sex) #Sex


ggplot(data, aes(x = demographics_age_index_ecg, fill = factor(outcome_afib_aflutter_new_post))) +
  geom_histogram(position = "identity", alpha = 0.6, bins = 30) +
  labs(title = "Age Distribution by New-Onset AF Outcome", fill = "AF Outcome")

data %>%
  mutate(sex = ifelse(demographics_birth_sex == 1, "Male", "Female")) %>%
  ggplot(aes(x = sex, fill = factor(outcome_afib_aflutter_new_post))) +
  geom_bar(position = "dodge") +
  labs(title = "Sex Distribution by AF Outcome", fill = "AF Outcome")
```

#Univariate Models
```{r}

```

##Missingness
```{r}
missing_summary <- data %>%
  summarise(across(everything(), ~ sum(is.na(.)))) %>%
  pivot_longer(everything(), names_to = "Variable name", values_to = "missing_n") %>%
  mutate(missing_pct = 100 * missing_n / nrow(data)) %>%
  arrange(desc(missing_pct))
```

```{r}
# add description, categories from data dictionary
filename <- "Data dictionary_stats competition 2025_final.xlsx"
data_dict <- read_excel(paste(path, filename, sep=""))

# i noticed some mismatch in variable names 
data_dict <- data_dict %>%
  mutate(`Variable name` = ifelse(`Variable name` == "NTproBNP_peri_highest","n_tpro_bnp_peri_highest", `Variable name`))


missing_summary <- missing_summary %>%
  left_join(data_dict %>% select(`Variable name`, Definition, `Variable category`), by = "Variable name")

write.csv(missing_summary, "missing_summary.csv")
```


#Missing Heatmap
```{r}
vis_miss(data[1:100, ]) +
  labs(title = "Missing Data Pattern (First 100 Rows)")
```


